### ISSUE TITLE
Does not replace hyphen ('-'), needs regex=True for Dataframe.replace()

### ISSUE THREAD

**Issue by fwzhao** [afrendeiro/toolkit#17]
https://github.com/afrendeiro/toolkit/blob/d579d5cad933c4d1a1a1983dbc7364a074ecf892/ngs_toolkit/general.py#L714

instead: 
experiment_matrix = experiment_matrix.replace("-", "_", regex=True)
comparison_table = comparison_table.replace("-", "_", regex=True)

edit: 
for some reason underscore '_' not showing above, only add regex etc. part.

**Comment by afrendeiro** [comment]
I cannot reproduce this. Please try:
```python
a = pd.DataFrame([["-", 1], [1, 2]]).replace("-", "_")
b = pd.DataFrame([["_", 1], [1, 2]])
assert (a == b).all().all()
c = pd.DataFrame([["-", 1], [pd.np.nan, 2]]).replace("-", "_")
d = pd.DataFrame([["_", 1], [1, 2]])
assert (c == d).all(1)[0]
```
I'm willing to add regex=True, but in my case I don't find the need so it would be good to understand this first.

**Comment by fwzhao** [comment]
I tested what you wrote, and this works. I don't know why I initially encountered this. Will close this for now, and reopen if necessary in the future.
