### ISSUE TITLE
R dataframe conversion bugs

### ISSUE THREAD

**Issue by fwzhao** [afrendeiro/toolkit#19]
https://github.com/afrendeiro/toolkit/blob/d579d5cad933c4d1a1a1983dbc7364a074ecf892/ngs_toolkit/general.py#L690-L692
With my version of R (etc.), I had to change to the following to work

def r2pandas_df(r_df):
    import numpy as np
    df = pd.DataFrame(np.asarray(r_df)) # No transposition
    df.columns = [s for s in r_df.columns.tolist()]
    df.index = [s for s in r_df.index.tolist()]
    return df

Perhaps this entire function is depreciated? I didn't really find a need to convert R data frame to Pandas DF

**Comment by fwzhao** [comment]
Versions of packages required - 
version of pandas:0.23.3
version of tqdm:4.23.1
version of rpy2:2.4.4
os has no version
version of matplotlib:2.2.2
version of numpy:1.14.5
version of pandas:0.23.3
version of seaborn:0.9.0
version of looper:0.6.0-rc1
version of scipy:0.14.0
version of ngs_toolkit:0.1.3.5.3
version of ngs_toolkit:0.1.3.5.3
version of tqdm:4.23.1
pypiper has no version
textwrap has no version

('no version' indicates package has no attribute '__version__')

------------------- Error message below --------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-8-65d0c14b0591> in <module>()
     19         covariates=None,
     20         alpha=alpha,  # not really used
---> 21         overwrite=True)
     22     atac_analysis.differential_results = atac_analysis.differential_results.append(res, ignore_index=True)

/home/fzhao/.local/lib/python2.7/site-packages/ngs_toolkit/general.pyc in differential_analysis(analysis, comparison_table, data_type, samples, covariates, output_dir, output_prefix, alpha, overwrite, distributed)
   1144         results = deseq_analysis(
   1145             count_matrix, experiment_matrix, comparison_table,
-> 1146             formula, output_dir, output_prefix, alpha=alpha, overwrite=overwrite)
   1147         return results
   1148 

/home/fzhao/.local/lib/python2.7/site-packages/ngs_toolkit/general.pyc in deseq_analysis(count_matrix, experiment_matrix, comparison_table, formula, output_dir, output_prefix, overwrite, alpha)
    738 
    739         # convert to pandas dataframe
--> 740         res2 = r2pandas_df(res)
    741         res2.loc[:, "comparison_name"] = comp
    742 

/home/fzhao/.local/lib/python2.7/site-packages/ngs_toolkit/general.pyc in r2pandas_df(r_df)
    688         import numpy as np
    689         df = pd.DataFrame(np.asarray(r_df)).T
--> 690         df.columns = [str(x) for x in r_df.colnames]
    691         df.index = [str(x) for x in r_df.rownames]
    692         return df

/home/fzhao/.local/lib/python2.7/site-packages/pandas/core/generic.pyc in __getattr__(self, name)
   4374             if self._info_axis._can_hold_identifiers_and_holds_name(name):
   4375                 return self[name]
-> 4376             return object.__getattribute__(self, name)
   4377 
   4378     def __setattr__(self, name, value):

AttributeError: 'DataFrame' object has no attribute 'colnames'

**Comment by afrendeiro** [comment]
Okay, these tests should check what is the type of the retrieved object from DESeq2:

```python
import numpy as np
import pandas as pd
from tqdm import tqdm
import rpy2
from rpy2.robjects import numpy2ri, pandas2ri
import rpy2.robjects as robjects
from rpy2.rinterface import RRuntimeError
numpy2ri.activate()
pandas2ri.activate()

def r2pandas_df(r_df):
    import numpy as np
    df = pd.DataFrame(np.asarray(r_df)).T
    df.columns = [str(x) for x in r_df.colnames]
    df.index = [str(x) for x in r_df.rownames]
    return df

df = pd.DataFrame(np.random.normal(0, 1, (100, 100)))

robjects.r('require("DESeq2")')
_as_data_frame = robjects.r('as.data.frame')

print(type(_as_data_frame(df)))
print(type(r2pandas_df(_as_data_frame(df))))
assert rpy2.robjects.vectors.DataFrame == type(_as_data_frame(df))
assert pd.DataFrame == type(r2pandas_df(_as_data_frame(df)))
```

**Comment by afrendeiro** [comment]
Please test  general.differential_analysis() function when you can @fwzhao
