### ISSUE TITLE
markdown readme doesn't render on pypi

### ISSUE THREAD

**Issue by nsheff** [afrendeiro/toolkit#26]
markdown readme doesn't render on pypi

See here:

https://pypi.org/project/ngs-toolkit/

you can solve it like this:

https://github.com/pepkit/peppy/blob/35da352ed44b1ee7551aa1c89d36111ac44b8ec3/setup.py#L53-L58

example: https://pypi.org/project/peppy/

**Comment by afrendeiro** [comment]
Thanks!
https://test.pypi.org/project/ngs-toolkit/0.1.4.1b0/
