### ISSUE TITLE
numpy version might be too low

### ISSUE THREAD

**Issue by fwzhao** [afrendeiro/toolkit#42]
https://github.com/afrendeiro/toolkit/blob/b0d0681ab89acc42df29e046c21f5f2a663865d9/requirements/requirements.txt#L1

Hi Andre,
With numpy version=1.15.0, while running ATACSeqAnalysis('blah').get_peak_gene_annotation(tss='different blah'), I encountered:
ModuleNotFoundError - No module named 'numpy.core._multiarray_umath'

A bit of googling and tab completion revealed that version 1.15 of numpy does not have this module (obviously) and this was fixed by upgrading to 1.16.

Thought I'd let you know (I checked the dev version and didn't see a change in the requirements).
Cheers,
F

**Comment by afrendeiro** [comment]
Thanks, will close when merging to master (soon).
