### ISSUE TITLE
Might be a bug: actually want to reduce to .unique() values

### ISSUE THREAD

**Issue by fwzhao** [afrendeiro/toolkit#43]
https://github.com/afrendeiro/toolkit/blob/37bb92df70e0558b146463fcaacf9ee786d2b7fa/ngs_toolkit/general.py#L985

I realized that there were duplicate lines being generated, and think that perhaps it might need unique() at the end of the groups, otherwise many redundancies in associations dataframe

At least for me, this is why the code is taking forever to run.

**Comment by afrendeiro** [comment]
You're right - nicely spotted!
Will close when merged to master.
