### ISSUE TITLE
plot_peak_characteristics error: Initializing dataframe with iterator

### ISSUE THREAD

**Issue by fwzhao** [afrendeiro/toolkit#44]
https://github.com/afrendeiro/toolkit/blob/37bb92df70e0558b146463fcaacf9ee786d2b7fa/ngs_toolkit/atacseq.py#L1280

Here - corrected version should have put sample_peak_lengths into a list.

    lengths = pd.melt(pd.DataFrame([sample_peak_lengths],
                                   index=[s.name for s in samples]).T,
                      value_name='peak_length',
                      var_name="sample_name").dropna()

**Comment by afrendeiro** [comment]
That was valid Python 2.
Python3's `map` function returns a lazy iterator while Python2 would return the results of the mapping function.

The `plot_peak_characteristics` function has been revamped in `dev`:
https://github.com/afrendeiro/toolkit/blob/dev/ngs_toolkit/atacseq.py#L1654 so I'm closing the issue
