### ISSUE TITLE
Typo in Example https://ngs-toolkit.readthedocs.io/en/latest/examples.html

### ISSUE THREAD

**Issue by sreichl** [afrendeiro/toolkit#52]
In the [example](https://ngs-toolkit.readthedocs.io/en/latest/examples.html) the variable **n_top** for the parameter **max_diff**  is not defined (default would be 1000).

```
# # perform enrichment analysis on differnetial region sets 
# # using LOLA, MEME-AME, HOMER and Enrichr 
analysis.differential_enrichment(     
directional=True,     
max_diff=**n_top**,     
sort_var="pvalue")
```

**Comment by afrendeiro** [comment]
Fixed in 9fa23023eca160525b7570b9fca823b25ff4a87c
Thanks!
