### ISSUE TITLE
ATACAnalysis feature request - make chrom_state_file / build more explicit

### ISSUE THREAD

**Issue by fwzhao** [afrendeiro/toolkit#54]
It could be really nice if the statement of which regulatory build was more explicit in chrom_state_file. 
For example - this could mean:
results/analysis.chrom_state_annotation.csv --> results/analysis.E002.chrom_state_annotation.csv
attribute E002_chrom_state_annotation for analysis object
 
Pro's:
- more immediately apparent in results directory
-allows for multiple chromatin states to be analyzed for mixed samples (e.g. PBMCs)

Con's:
- too specialized?

**Comment by afrendeiro** [comment]
I think this could be solved by adding a "output_prefix" argument to this (and the remaining functions to annotate features). This way, there is a reasonable default "chrom_state_annotation" that can be changed by the user.

Sounds good?

**Comment by fwzhao** [comment]
Sounds great :)
