### ISSUE TITLE
typo in attr name (organism)

### ISSUE THREAD

**Issue by fwzhao** [afrendeiro/toolkit#58]
https://github.com/afrendeiro/toolkit/blob/1dfa4d0a8b30ccb9e9be57b7663f798a5016ab5e/ngs_toolkit/atacseq.py#L1846

**Comment by afrendeiro** [comment]
Nice catch, thanks!

By the way, I haven't used that function in a long time, it's on the list to be revamped. Let me know if you find it useful.

**Comment by afrendeiro** [comment]
39105d1fb2642a8a948861e2cf646d048f8c355b

**Comment by afrendeiro** [comment]
Added also testing for this function cc78832ddd9ef37fcaa2e55562223a486b66b8e1
