### ISSUE TITLE
Motif vs. Meme

### ISSUE THREAD

**Issue by fwzhao** [afrendeiro/toolkit#63]
https://github.com/afrendeiro/toolkit/blob/eccb6fce09069417decdf52089550778d87117ce/ngs_toolkit/analysis.py#L5593-L5613

Is there a reason that differential enrichment recognizes "meme" and collect differential enrichment recognizes "motif" as one of the steps? the two are also somewhat used interchangeably in collect differential enrichment

**Comment by afrendeiro** [comment]
No, it's an inconsistency.

I will rename "motif" to "meme" everywhere to align it with the nomenclature elsewhere (in general the name of the tool is used) and to avoid confusion with "homer".
